// priority: 100

hide1(['appliedenergistics2:2_cubed_spatial_cell_component', 'appliedenergistics2:16_cubed_spatial_cell_component', 'appliedenergistics2:128_cubed_spatial_cell_component', 'appliedenergistics2:2_cubed_spatial_storage_cell', 'appliedenergistics2:16_cubed_spatial_storage_cell', 'appliedenergistics2:128_cubed_spatial_storage_cell', 'appliedenergistics2:spatial_anchor', 'appliedenergistics2:spatial_pylon', 'appliedenergistics2:spatial_io_port']);
hide1(['appliedenergistics2:engineering_processor', 'appliedenergistics2:calculation_processor', 'appliedenergistics2:logic_processor', 'appliedenergistics2:printed_silicon', 'appliedenergistics2:printed_calculation_processor', 'appliedenergistics2:printed_engineering_processor', 'appliedenergistics2:printed_logic_processor', 'appliedenergistics2:calculation_processor_press', 'appliedenergistics2:engineering_processor_press', 'appliedenergistics2:silicon', 'appliedenergistics2:name_press', 'appliedenergistics2:silicon_press', 'appliedenergistics2:logic_processor_press']);
hide1(['appliedenergistics2:portable_cell', 'appliedenergistics2:4k_portable_cell', 'appliedenergistics2:16k_portable_cell', 'appliedenergistics2:64k_portable_cell', 'appliedenergistics2:1k_cell_component', 'appliedenergistics2:4k_cell_component', 'appliedenergistics2:16k_cell_component', 'appliedenergistics2:64k_cell_component', 'appliedenergistics2:empty_storage_cell', 'appliedenergistics2:1k_fluid_cell_component', 'appliedenergistics2:4k_fluid_cell_component', 'appliedenergistics2:16k_fluid_cell_component', 'appliedenergistics2:64k_fluid_cell_component', 'appliedenergistics2:creative_storage_cell', 'appliedenergistics2:molecular_assembler', 'appliedenergistics2:condenser']);

hide1(['appliedenergistics2:fluix_dust', 'appliedenergistics2:certus_quartz_dust', 'appliedenergistics2:nether_quartz_dust', 'appliedenergistics2:certus_quartz_crystal', 'appliedenergistics2:charged_certus_quartz_crystal', 'appliedenergistics2:fluix_crystal', 'appliedenergistics2:quartz_ore', 'appliedenergistics2:charged_quartz_ore', 'appliedenergistics2:fluix_crystal_seed']);

hide4('appliedenergistics2:', ['sky_stone', 'smooth_sky_stone', 'sky_stone_brick', 'sky_stone_small_brick', 'fluix', 'quartz', 'chiseled_quartz', 'quartz_pillar'], '_', ['wall', 'stairs', 'slab']);

hide4('appliedenergistics2:', ['certus_quartz', 'nether_quartz'], '_', ['axe', 'hoe', 'shovel', 'pickaxe', 'sword']);

hide4('appliedenergistics2:', colors, '_', ['paint_ball', 'lumen_paint_ball',  'covered_cable', 'covered_dense_cable']);

hide2('appliedenergistics2:', ['quartz_pillar', 'sky_stone_brick', 'sky_stone_small_brick', 'sky_stone_block', 'fluix_block', 'smooth_sky_stone_block', 'quartz_block', 'chiseled_quartz_block', 'sky_stone_chest', 'smooth_sky_stone_chest', 'color_applicator', 'matter_cannon', 'debug_part_placer', 'energy_cell', 'dense_energy_cell', 'creative_energy_cell', 'charged_staff', 'entropy_manipulator', 'quartz_vibrant_glass', 'quartz_fixture', 'sky_compass', 'grindstone', 'crank', 'inscriber', 'charger', 'nether_quartz_seed', 'purified_nether_quartz_crystal', 'vibration_chamber', 'light_detector', 'sky_dust', 'gold_dust', 'iron_dust', 'matter_ball', 'flour', 'wireless_access_point', 'wireless_receiver', 'wireless_booster', 'wireless_terminal', 'fluix_pearl', 'identity_annihilation_plane', 'wooden_gear', 'nether_quartz_wrench', 'nether_quartz_cutting_knife', 'cable_energy_acceptor', 'dark_monitor', 'monitor', 'encoded_pattern', 'fluix_covered_dense_cable', 'fluix_covered_cable']);
