// priority: 100

hide1(['minecraft:shulker_box', 'minecraft:orange_shulker_box', 'minecraft:white_shulker_box', 'minecraft:white_shulker_box', 'minecraft:magenta_shulker_box', 'minecraft:light_blue_shulker_box', 'minecraft:yellow_shulker_box', 'minecraft:lime_shulker_box', 'minecraft:pink_shulker_box', 'minecraft:gray_shulker_box', 'minecraft:black_shulker_box', 'minecraft:red_shulker_box', 'minecraft:green_shulker_box', 'minecraft:brown_shulker_box', 'minecraft:blue_shulker_box', 'minecraft:purple_shulker_box', 'minecraft:cyan_shulker_box', 'minecraft:light_gray_shulker_box', 'minecraft:shulker_shell', 'minecraft:shulker_spawn_egg']);
hide1(['minecraft:end_stone', 'minecraft:end_stone_bricks', 'minecraft:end_stone_brick_stairs', 'minecraft:end_stone_brick_slab', 'minecraft:end_rod', 'minecraft:end_portal_frame', 'minecraft:ender_chest', 'minecraft:end_stone_brick_wall', 'minecraft:end_crystal']);
hide1(['minecraft:dragon_head', 'minecraft:dragon_breath', 'minecraft:chorus_plant', 'minecraft:chorus_flower', 'minecraft:chorus_fruit', 'minecraft:popped_chorus_fruit', 'minecraft:purpur_pillar', 'minecraft:purpur_block', 'minecraft:purpur_stairs', 'minecraft:purpur_slab']);

hide1(['minecraft:nether_brick', 'minecraft:nether_wart', 'minecraft:netherite_boots', 'minecraft:netherite_leggings', 'minecraft:nether_gold_ore', 'minecraft:nether_brick_slab', 'minecraft:netherrack', 'minecraft:nether_bricks', 'minecraft:cracked_nether_bricks', 'minecraft:chiseled_nether_bricks', 'minecraft:nether_brick_stairs', 'minecraft:nether_quartz_ore', 'minecraft:nether_wart_block', 'minecraft:red_nether_brick_wall', 'minecraft:nether_brick_wall', 'minecraft:nether_brick_fence', 'minecraft:nether_sprouts', 'minecraft:ancient_debris', 'minecraft:netherite_block', 'minecraft:red_nether_brick_slab', 'minecraft:red_nether_brick_stairs', 'minecraft:red_nether_bricks', 'minecraft:netherite_ingot', 'minecraft:nether_star', 'minecraft:netherite_sword', 'minecraft:netherite_shovel', 'minecraft:netherite_pickaxe', 'minecraft:netherite_axe', 'minecraft:netherite_hoe', 'minecraft:netherite_helmet', 'minecraft:netherite_chestplate', 'minecraft:shroomlight', 'weeping_vines', 'twisting_vines']);
hide1(['minecraft:crimson_nylium', 'minecraft:crimson_planks', 'minecraft:crimson_stem', 'minecraft:stripped_crimson_stem', 'minecraft:stripped_crimson_hyphae', 'minecraft:crimson_hyphae', 'minecraft:crimson_slab', 'minecraft:crimson_stairs', 'minecraft:crimson_fungus', 'minecraft:crimson_door', 'minecraft:crimson_button', 'minecraft:crimson_fence_gate', 'minecraft:crimson_trapdoor', 'minecraft:crimson_pressure_plate', 'minecraft:crimson_sign', 'minecraft:crimson_fence', 'minecraft:crimson_roots']);
hide1(['minecraft:warped_nylium', 'minecraft:warped_planks', 'minecraft:warped_stem', 'minecraft:stripped_warped_stem', 'minecraft:stripped_warped_hyphae', 'minecraft:warped_hyphae', 'minecraft:warped_slab', 'minecraft:warped_stairs', 'minecraft:warped_wart_block', 'minecraft:warped_door', 'minecraft:warped_button', 'minecraft:warped_fence_gate', 'minecraft:warped_trapdoor', 'minecraft:warped_pressure_plate', 'minecraft:warped_sign', 'minecraft:warped_fence', 'minecraft:warped_roots', 'minecraft:warped_fungus', 'minecraft:warped_fungus_on_a_stick']);
hide1(['minecraft:blackstone', 'minecraft:blackstone_slab', 'minecraft:blackstone_stairs', 'minecraft:gilded_blackstone', 'minecraft:polished_blackstone', 'minecraft:polished_blackstone_slab', 'minecraft:polished_blackstone_stairs', 'minecraft:chiseled_polished_blackstone', 'minecraft:polished_blackstone_bricks', 'minecraft:polished_blackstone_button', 'minecraft:polished_blackstone_pressure_plate', 'minecraft:polished_blackstone_brick_wall', 'minecraft:polished_blackstone_wall', 'minecraft:blackstone_wall', 'minecraft:cracked_polished_blackstone_bricks', 'minecraft:polished_blackstone_brick_stairs', 'minecraft:polished_blackstone_brick_slab']);
hide1(['minecraft:basalt', 'minecraft:polished_basalt', 'minecraft:respawn_anchor', 'minecraft:crying_obsidian', 'minecraft:glowstone', 'minecraft:glowstone_dust', 'minecraft:soul_sand', 'minecraft:soul_soil', 'minecraft:soul_torch', 'minecraft:soul_lantern', 'minecraft:magma_cream', 'minecraft:magma_block', 'minecraft:blaze_rod', 'minecraft:blaze_powder', 'minecraft:ghast_tear', 'minecraft:fire_charge', 'minecraft:soul_campfire', 'minecraft:quartz']);

hide1(['minecraft:andesite', 'minecraft:polished_andesite', 'minecraft:polished_andesite_stairs', 'minecraft:andesite_stairs', 'minecraft:polished_andesite_slab', 'minecraft:andesite_slab', 'minecraft:andesite_wall']);
hide1(['minecraft:granite', 'minecraft:polished_granite', 'minecraft:polished_granite_stairs', 'minecraft:granite_stairs', 'minecraft:polished_granite_slab', 'minecraft:granite_slab', 'minecraft:granite_wall']);
hide1(['minecraft:diorite', 'minecraft:polished_diorite', 'minecraft:polished_diorite_stairs', 'minecraft:diorite_stairs', 'minecraft:polished_diorite_slab', 'minecraft:diorite_slab', 'minecraft:diorite_wall']);
hide1(['minecraft:sponge', 'minecraft:wet_sponge', 'minecraft:lava_bucket', 'minecraft:water_bucket', 'minecraft:lava_bucket', 'minecraft:water_bucket', 'minecraft:milk_bucket', 'minecraft:pufferfish_bucket', 'minecraft:salmon_bucket', 'minecraft:cod_bucket', 'minecraft:tropical_fish_bucket', 'minecraft:totem_of_undying', 'minecraft:heart_of_the_sea', 'minecraft:conduit', 'minecraft:nautilus_shell', 'minecraft:crossbow' , 'minecraft:bow']);

hide2('minecraft:', ['golden_horse_armor', 'iron_horse_armor', 'diamond_horse_armor', 'potion', 'splash_potion', 'lingering_potion', 'brewing_stand', 'enchanted_book', 'enchanting_table', 'bucket', 'arrow', 'spectral_arrow', 'tipped_arrow', 'netherite_block', 'ancient_debris', 'netherite_ingot', 'netherite_scrap', 'torch', 'jack_o_lantern', 'lantern', 'sea_lantern', 'wooden_sword', 'oak_boat', 'spruce_boat', 'birch_boat', 'jungle_boat', 'acacia_boat', 'dark_oak_boat', 'honey_bottle', 'glass_bottle', 'honey_block', 'potion', 'gold_ore', 'iron_ore', 'coal_ore', 'diamond_ore', 'redstone_ore', 'redstone_lamp', 'dispenser', 'dropper', 'hopper', 'piston', 'sticky_piston', 'hopper_minecart', 'glistering_melon_slice', 'shield', 'golden_carrot', 'elytra', 'smithing_table', 'dried_kelp_block', 'blast_furnace', 'bedrock', 'skeleton_skull', 'wither_skeleton_skull', 'zombie_head', 'creeper_head', 'beacon', 'enchanted_golden_apple', 'carrot_on_a_stick', 'infested_stone', 'infested_cobblestone', 'infested_stone_bricks', 'infested_mossy_stone_bricks', 'infested_cracked_stone_bricks', 'infested_chiseled_stone_bricks', 'lily_pad', 'vine', 'fletching_table', 'experience_bottle', 'golden_apple', 'phantom_membrane', 'target', 'bell', 'lodestone', 'loom']);

hide1(['minecraft:emerald_ore', 'minecraft:emerald', 'minecraft:lapis_ore', 'minecraft:lapis_lazuli']);

hide3('minecraft:', colors, '_glazed_terracotta');
hide3('minecraft:', colors, '_terracotta');
hide3('minecraft:', colors, '_carpet');
hide1(['minecraft:flower_banner_pattern', 'minecraft:skull_banner_pattern', 'minecraft:creeper_banner_pattern', 'minecraft:mojang_banner_pattern', 'minecraft:globe_banner_pattern', 'minecraft:piglin_banner_pattern']);
hide3('minecraft:', colors, '_banner');
hide4('minecraft:', colors, '_concrete', ['', '_powder']);

hide3('minecraft:', ['oak', 'spruce', 'birch', 'jungle', 'acacia', 'dark_oak'], '_wood');
hide3('minecraft:stripped_', ['oak', 'spruce', 'birch', 'jungle', 'acacia', 'dark_oak'], '_wood');

hide4('minecraft:', ['golden', 'iron', 'diamond', 'chainmail', 'netherite'], '_', ['helmet', 'chestplate', 'leggings', 'boots']);
hide4('minecraft:', ['golden', 'stone', 'iron', 'diamond', 'netherite'], '_', ['pickaxe', 'axe', 'shovel', 'hoe', 'sword']);
hide2('minecraft:', ['quartz_slab', 'smooth_quartz', 'chiseled_quartz_block', 'quartz_bricks', 'quartz_pillar', 'quartz_stairs', 'smooth_quartz_stairs', 'smooth_quartz_slab', 'anvil', 'chipped_anvil', 'damaged_anvil']);

hide1(['minecraft:prismarine_slab', 'minecraft:prismarine_brick_slab', 'minecraft:dark_prismarine_slab', 'minecraft:prismarine', 'minecraft:prismarine_bricks', 'minecraft:dark_prismarine', 'minecraft:prismarine_stairs', 'minecraft:prismarine_brick_stairs', 'minecraft:dark_prismarine_stairs', 'minecraft:prismarine_crystals', 'minecraft:prismarine_shard', 'minecraft:prismarine_wall']);

hide2('#minecraft:', ['beds']);
