onEvent('recipes', event => {
    function dron(I, O) { event.custom({ type: 'pneumaticcraft:amadron', input: I, output: O, static: true, maxStock: 100 }); }
    function ama(T, A, B, N) { return { type: T, id: A, amount: B, "nbt": N }; }
    function _f(A, B, N) { return ama('FLUID', A, B, N); }
    function _i(A, B, N) { return ama('ITEM', A, B, N); }
    //dron(_f('pneumaticcraft:oil', 100000), _i('minecraft:diamond', 1));

    //dron(_i('minecraft:stone', 1), _i('minecraft:written_book', 1, "{pages:['{\"text\":\"      *SOS SIGNAL*\\\\n      *SOS SIGNAL*\\\\n      *SOS SIGNAL*\"}'],author:\"SOS\",title:\"SOS\",resolved:true}"));

    //dron(_i('minecraft:written_book', 1, "{pages:['{\"text\":\"      *SOS SIGNAL*\\\\n      *SOS SIGNAL*\\\\n      *SOS SIGNAL*\"}'],author:\"SOS\",title:\"SOS\",resolved:true}"), _i('immersiveengineering:reinforced_crate', 1, '{BlockEntityTag:{inventory:[{Slot:0b,ForgeCaps:{Parent:{Size:21,Items:[]}},id:"immersiveengineering:revolver",Count:1b,tag:{bullets:[]}},{Slot:1b,id:"immersiveengineering:turret_gun",Count:2b},{Slot:2b,id:"immersiveengineering:armor_piercing",Count:64b},{Slot:3b,id:"immersiveengineering:armor_piercing",Count:64b},{Slot:4b,id:"immersiveengineering:connector_lv_relay",Count:4b},{Slot:5b,id:"immersiveengineering:connector_lv",Count:4b},{Slot:6b,id:"immersiveengineering:wirecoil_copper_ins",Count:8b},{Slot:7b,id:"factoriores:electrical_miner",Count:1b},{Slot:8b,id:"mekanismgenerators:solar_generator",Count:1b,tag:{mekData:{}}},{Slot:9b,id:"mekanism:canteen",Count:1b,tag:{mekData:{GasTanks:[{Tank:0b,stored:{gasName:"mekanism:nutritional_paste",amount:20000L}}]}}},{Slot:10b,id:"immersiveengineering:pickaxe_steel",Count:1b,tag:{Damage:0}},{Slot:11b,id:"extendedcrafting:compressor",Count:1b},{Slot:12b,id:"create:schematic_table",Count:1b},{Slot:13b,id:"create:mechanical_saw",Count:1b},{Slot:14b,id:"create:hand_crank",Count:1b},{Slot:15b,id:"create:goggles",Count:1b},{Slot:16b,id:"diregoo:gooscanner",Count:1b},{Slot:17b,id:"adpother:aerometer",Count:1b,tag:{Damage:0}},{Slot:18b,id:"immersiveengineering:razor_wire",Count:64b},{Slot:19b,id:"immersiveengineering:armor_steel_legs",Count:1b,tag:{Damage:0}},{Slot:20b,id:"minecraft:leather_chestplate",Count:1b,tag:{Damage:0}},{Slot:21b,id:"minecraft:leather_boots",Count:1b,tag:{Damage:0}},{Slot:22b,id:"ftbquests:book",Count:1b},{Slot:23b,id:"pneumaticcraft:kerosene_lamp",Count:1b,tag:{BlockEntityTag:{SavedTanks:{Tank:{FluidName:"immersivepetroleum:diesel",Amount:2000}}}}},{Slot:24b,id:"immersiveengineering:electric_lantern",Count:1b},{Slot:25b,id:"immersiveengineering:capacitor_lv",Count:1b},{Slot:26b,id:"backpacked:backpack",Count:1b}],id:"immersiveengineering:woodencrate"},display:{Lore:[\'"(+NBT)"\']}}'));
});
