
[Config]
	#Change to 'true' if you want to disable Ender Eye to be thrown in the air
	AntiEye = true
	#Change to 'false' if you want to reactivate End Portals
	AntiEnd = true
	#Change to 'false' if you want to reactivate Nether Portals
	AntiNether = true

